name: prac5
description: "A 7 practice RKMP app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  google_fonts: ^6.3.2
  logger: ^2.6.2

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

#  my_package:
#    git:
#      url: https://github.com/username/my_package.git
#      ref: main
#      path: lib
#
#
#  local_package:
#     path: ../example/local_package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
